name: Descargar repositorio
on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
        
      - run: ls -la

      - name: Descargar proyecto
        uses: actions/upload-artifact@v4
        with:
          name: mi-proyecto-completo       
          path: .                         
          retention-days: 7